
name: Action

on:
  workflow_dispatch:

    inputs:
      shell:
        description: 'shell'
        required: true
        default: 'ls ; '
        
jobs:
  conftest:
    name: Validate via personal conftest policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate via personal conftest policies
        uses: docker://openpolicyagent/conftest:latest
        env:
          CONFTEST_POLICIES: git::https://github.com/iamleot/conftest-policies.git//policy/github
        with:
          args: test --all-namespaces --update "${{ env.CONFTEST_POLICIES }}" .github/workflows
